### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by samratghosh291** [Hackerspace2023/HackerSpace#10]
The README file of our project is essential for providing information about the project, how to use it, and how to contribute effectively. However, it may be outdated, lacking crucial information, or needing a fresh update to reflect recent changes.

**Comment by Illuminati9** [comment]
Hey @samratghosh291 , I would like to work on this issue under hacktoberfest'23. Can you assign it to me

**Comment by infiniteltd** [comment]
I would love to take up this issue.

**Comment by samratghosh291** [comment]
@Illuminati9 Thank you!!  for your interest. Happy Coding 🚀

**Comment by samratghosh291** [comment]
@infiniteltd you can raise another issue and then asking for assigning.

**Comment by Illuminati9** [comment]
Hey @samratghosh291 , Can you explain the issue clearly so that i can start working on it.

**Comment by samratghosh291** [comment]
@Illuminati9 design the Readme.md file so that it can clearly describe about the project.
Certainly, here are the basic points to cover in a good README.md:

1. Title and Description
2. Table of Contents
3. Installation
4. Usage
7. Contributing
Contact Information
Demo or Screenshots
This is the basic features inside a Readme.md should cover.  But you can add by yourself many things is already covered...decorate and butify it.
