### ISSUE TITLE
Enhance UI

### ISSUE THREAD

**Issue by sampath-kumaramd** [Hackerspace2023/HackerSpace#27]
Hey this one not look good enough in white theme.

![image](https://github.com/Hackerspace2023/HackerSpace/assets/84168369/5865f052-231b-4546-bf02-d508f0a0fdff)

**Comment by sampath-kumaramd** [comment]
may i re-create this one

**Comment by ShekharHans** [comment]
@sampath-kumaramd As @Rohxn16 already working omn this, so you can make another issue and asking for asign you.
