### ISSUE TITLE
Redesign the footer and update the footer links

### ISSUE THREAD

**Issue by arpankumarde** [Hackerspace2023/HackerSpace#28]
The current Footer is old fashioned and the footer links are not of **HackerSpace** Official community.

The Footer needs an immediate fix. A design suggestion can be similar to that of the [Hacktoberfest](https://hacktoberfest.com/) Website Footer.
Also, the links needs to be updated and they should redirect to the present HackerSpace community socials.

**Comment by therefat** [comment]
assign me

**Comment by arpankumarde** [comment]
@therefat and @shreyanshig the work on the footer has been completed, creating the PR was just left, which will be done in a moment
